;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2020/8/14 17:31:48

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1056	1056	; hadoop原理 hadoop\hadoop\hadoop原理.htm
#define IDH_1046	1046	; hadoop指令集 hadoop\hadoop\hadoop指令集.htm
#define IDH_1024	1024	; hadoop配置与优化 hadoop\hadoop\hadoop配置与优化.htm
#define IDH_1020	1020	; 调度器 hadoop\yarn\yarn调度.htm
#define IDH_1011	1011	; yarn配置与优化 hadoop\yarn\yarn配置与优化.htm
#define IDH_1051	1051	; hbase指令集 hadoop\hbase\hbase指令集.htm
#define IDH_1042	1042	; hbaseAPI hadoop\hbase\hbaseAPI.htm
#define IDH_1041	1041	; hbase原理 hadoop\hbase\hbase原理.htm
#define IDH_1050	1050	; hbase配置与优化 hadoop\hbase\hbase配置与优化.htm
#define IDH_1054	1054	; protocol hadoop\hbase\protocol buffer.htm
#define IDH_1071	1071	; hive-client hadoop\hive\hive-client.htm
#define IDH_1034	1034	; hive优化 hadoop\hive\hive优化.htm
#define IDH_1035	1035	; hive语法 hadoop\hive\hive语法.htm
#define IDH_1037	1037	; hive 自定义函数 hadoop\hive\hive自定义函数.htm
#define IDH_1052	1052	; zookeeper概念 hadoop\zookeeper\zookeeper概念.htm
#define IDH_1048	1048	; zookeeper指令集 hadoop\zookeeper\zookeeper指令集.htm
#define IDH_1007	1007	; kafka概念 hadoop\kafka\kafka概念.htm
#define IDH_1047	1047	; kafka指令集 hadoop\kafka\kafka指令集.htm
#define IDH_1053	1053	; kafka配置 hadoop\kafka\kafka配置.htm
#define IDH_1080	1080	; spark本地调试 hadoop\spark\spark本地调试.htm
#define IDH_1093	1093	; kerberos概念 hadoop\kerberos\kerberos概念.htm
#define IDH_1095	1095	; elasticsearch配置 hadoop\elasticsearch\elasticsearch配置.htm
#define IDH_1096	1096	; kibana配置 hadoop\kibana\kibana配置.htm
#define IDH_1063	1063	; 基本原理 java\jvm\基本原理.htm
#define IDH_1069	1069	; 概念 java\metrics\概念.htm
#define IDH_1076	1076	; http协议 java\http\http协议.htm
#define IDH_1028	1028	; java请求调用 java\http\java请求调用.htm
#define IDH_1005	1005	; axis java\http\axis.htm
#define IDH_1065	1065	; jersey java\http\jersey.htm
#define IDH_1044	1044	; log4j java\log4j\log4j.htm
#define IDH_1022	1022	; 反射 java\基础\反射.htm
#define IDH_1013	1013	; 解析 java\xml\解析.htm
#define IDH_1012	1012	; java类 java\面试\java.htm
#define IDH_1078	1078	; 系统篇 java\面试\系统篇.htm
#define IDH_1085	1085	; 分布式 java\面试\分布式.htm
#define IDH_1086	1086	; 大数据 java\面试\大数据.htm
#define IDH_1087	1087	; jvm java\面试\jvm.htm
#define IDH_1068	1068	; puppet ruby\puppet\puppet.htm
#define IDH_1033	1033	; js基础 前端\javascript\js基础.htm
#define IDH_1036	1036	; js插件 前端\javascript\js插件.htm
#define IDH_1001	1001	; 基础ajax 前端\ajax\ajax.html
#define IDH_1000	1000	; juery_ajax 前端\ajax\jquery ajax.html
#define IDH_1002	1002	; DWR 前端\ajax\dwr.html
#define IDH_1023	1023	; emberJs 前端\emberJs\emberJs.htm
#define IDH_1077	1077	; 数据库类 数据库\database.htm
#define IDH_1017	1017	; oracle基础篇 数据库\oracle\oracle基础篇.htm
#define IDH_1039	1039	; oracle高级篇 数据库\oracle\oracle高级篇.html
#define IDH_1029	1029	; oracle优化篇 数据库\oracle\oracle优化篇.html
#define IDH_1038	1038	; oracle工具篇 数据库\oracle\oracle工具篇.html
#define IDH_1060	1060	; mysql基础篇 数据库\mysql\mysql基础篇.htm
#define IDH_1062	1062	; mysql高级篇 数据库\mysql\mysql高级篇.htm
#define IDH_1083	1083	; redis基础篇 数据库\redis\redis基础篇.htm
#define IDH_1091	1091	; redis高级篇 数据库\redis\redis高级篇.htm
#define IDH_1084	1084	; redis命令行 数据库\redis\redis命令行.htm
#define IDH_1015	1015	; linux命令 os\linux\linux命令.htm
#define IDH_1032	1032	; shell编程 os\linux\shell.htm
#define IDH_1070	1070	; 产品指令 os\linux\产品指令.htm
#define IDH_1014	1014	; windows命令 os\windows\windows命令.htm
#define IDH_1027	1027	; 分流算法 算法\分流算法.htm
#define IDH_1010	1010	; 技巧 工具\utils.htm
#define IDH_1074	1074	; ambari 产品\ambari.htm
#define IDH_1075	1075	; JetBrain 产品\JetBrain.htm
#define IDH_1072	1072	; 资料网址 资料网址.htm
